services:
  postgres:
    image: postgres:17-alpine
    container_name: shortlink-postgres

    environment:
      POSTGRES_USER: shortlink
      POSTGRES_PASSWORD: shortlink
      POSTGRES_DB: shortlink
    
    ports:
      - "5432:5432"
    
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: